spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inflowdb
    username: inflow
    password: inflow

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true